### PR TITLE
New features and some bug fixes

### PR DESCRIPTION
**Pull request by AmjadHD**
## New Features

    - you can now save previewed images
    - you can now open downloaded images
    - added svg support
    - added support for absolute paths
    - added search modes
    - downloading and rendering images is non blocking

## Fixes
    - #11 : svg support
    - #20 : support for absolute paths
    - #24 : sublime text hangs for too long when hovering over a url

### CODE REVIEW

**Comment by alvesjtiago** [comment]
@AmjadHD this looks awesome! Thank you so much.
I'll review this later today and merge as soon as possible. Amazing work!

**Comment by alvesjtiago** [comment]
@AmjadHD once again, amazing work! I was having trouble getting the svg conversion to work so I had to change this line:

```subprocess.call(['magick', tmp_file, png], shell=True)```

to this:

```subprocess.call(['magick ' + tmp_file + ' ' + png], shell=True)```

Did you experience the same problem?

**Comment by AmjadHD** [comment]
no, in fact the first form is safer (the docs says so) cause it takes care of quotation and escaping, what os are you using and is magick in your path ?

**Comment by alvesjtiago** [comment]
Yes it is. I'm using macOS. I also found it strange but it was the only way it worked for me. Can you confirm that it also works for you? Otherwise I'll try to figure out where each version works and add a conditional.

**Comment by AmjadHD** [comment]
No problem, all forms work fine for me, you can go with that .

**Comment by alvesjtiago** [comment]
Perfect. If an issue arises because of that we'll revert it back and figure out how to deal with it.
Thank you once again for the improvements.

**Comment by AmjadHD** [comment]
I think you should announce for releases in the sublime forum, that should give a boost to the install rate.

**Comment by alvesjtiago** [comment]
Good idea, will do.

**Pull request merged**
