### PR TITLE
resize popup on click and few other features

### PR DESCRIPTION
**Pull request by AmjadHD**
popups sometimes takes a lot of the screen space, so i added an option to resize them.
that's the main reason i created this pull request
the link to open the image in new view and the size in ko are also good features i think..

fix

### CODE REVIEW

**Comment by alvesjtiago** [comment]
@AmjadHD that looks awesome! Thank you for contributing. I'll be reviewing it and merging as soon as possible.

One thing I noticed is that sometimes you removed some parentheses and other times you omitted them. I haven't set any code rules so that's definitely my fault but it would be great if you could standardize the if clauses you modified. Would that be possible?

Once again, thank you so much for adding both features 😊

**Comment by AmjadHD** [comment]
You are welcomed @alvesjtiago. The standarized way is to only use parenths when necessary ex: you don't need parenths for:
```python
if a == 5:
```
or
```python
if a and not b:
```
but you need them for  cases when you're not sure how will the interpreter get your boolean expression, such as:
```python
if a == 5 or not a and b:
```
this here needs to be clarified by parenths to make sure you and the interpreter are on the same wave, otherwise you better not use parenths, at least that's how i do and all the people i examined their codes.
Hope i got your question straight.

**Comment by AmjadHD** [comment]
can you make sure i didn't make any mistakes and break the plugin ?

**Comment by AmjadHD** [comment]
oh crapp!! I ruined it, do you know how to undo a commit ? I'm a newbie in github.

**Comment by alvesjtiago** [comment]
haha don't worry 😊 just revert the commit locally and push the changes to your branch. You can find more info here: https://stackoverflow.com/questions/36168839/how-to-remove-commits-from-pull-request

**Comment by AmjadHD** [comment]
All right fixed it, thanks .

**Comment by AmjadHD** [comment]
I don't know why, although I'm pushing those commits (from a local repository) , github doesn't consider them mine ??

**Comment by alvesjtiago** [comment]
That's strange. What does `git log` show on your end?
Sorry that I still haven't had time to review and merge but I'll do it soon.

**Pull request merged**
