### PR TITLE
0.0.20

### PR DESCRIPTION
**Pull request by AmjadHD**
Hover Image Preview v0.0.20
===========================

## New Features

- added support for "ico" and "webp" image formats
- added a "convert to.." option to convert from one image format to another
- you can now add more image formats through the settings
- better link style

## Fixes
- "imgname.ext is already in $PATH_TO_TEMP_DIR/tmp_image.ext" on save error
- platform dependent handling of the conversion command

### CODE REVIEW

**Comment by alvesjtiago** [comment]
@AmjadHD once again thank you for your contributions.

Conversion is only working for me if I set shell to `False` on the subprocess magick call. Do you see any problem with that?

**Comment by AmjadHD** [comment]
I think `shell=True` was the problem since the beginning, can you try `subprocess.call(['magick', inp, out])` without try and except block and see if it works ?

**Comment by alvesjtiago** [comment]
It does. Just merged and released a new version.

**Comment by AmjadHD** [comment]
Can you change magick to:

```python
def magick(inp, out):
    try:
        subprocess.call(["magick", inp, out], shell=True)
    except:
        subprocess.call(["magick", inp, out])
```
`shell=True` is required for windows to hide the console.

**Comment by alvesjtiago** [comment]
@AmjadHD would it make sense to detect if it's running on Windows and act accordingly?

**Comment by AmjadHD** [comment]
The code above should work fine on all os's.

**Comment by alvesjtiago** [comment]
@AmjadHD I understand though I'd like to make sure `shell=True` is not the default call for all OS's. Take a look at some of the answers here: https://stackoverflow.com/questions/3172470/actual-meaning-of-shell-true-in-subprocess

**Comment by AmjadHD** [comment]
I think we can go with my code cause `shell=True` means nothing on windows other than hiding the console, cause windows has no bourne again shell, alternativly we can test the platform and act accordingly.

**Comment by AmjadHD** [comment]
Alternatively if you're suspicious about this shell we can drop it and use startupinfo() and set some flags.

**Comment by AmjadHD** [comment]
One more thing to mention is that makedirs is not needed cause the magick command does that automatically.

**Comment by alvesjtiago** [comment]
@AmjadHD the magick command does not seem to create a folder on MacOS so I've manually added it. Also just released version 0.0.21 with the shell fix for windows. Let me know if it works.

**Comment by AmjadHD** [comment]
yes it does, I noticed you added spaces between links, I tried to make them as compact as possible, so that to make them look like buttons and reduce the amount of empty space for small images.

**Pull request merged**
